### ISSUE TITLE
process panic

### ISSUE THREAD

**Issue by synodriver** [newpanjing/gofound#14]
使用最新的release，使用python客户端运行test.py
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x188 pc=0xcc1df7]

goroutine 7 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
        /home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:230
github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
        /home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:235
github.com/syndtr/goleveldb/leveldb.(*DB).Get(0xc00040a680?, {0xc002ed87a8?, 0x8?, 0x6?}, 0xc002ed87a8?)
        /home/runner/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:838 +0x57
gofound/searcher/storage.(*LeveldbStorage).Get(0xc00040a680, {0xc002ed87a8, 0x6, 0x8})
        /home/runner/work/gofound/gofound/searcher/storage/leveldb_storage.go:88 +0x4b
gofound/searcher.(*Engine).addInvertedIndex(0xc0004380c0, {0xc0051bb8b0, 0x6}, 0x3e8)
        /home/runner/work/gofound/gofound/searcher/engine.go:208 +0x165
gofound/searcher.(*Engine).AddDocument(0xc0004380c0, 0xc002ee4080)
        /home/runner/work/gofound/gofound/searcher/engine.go:187 +0xf7
gofound/searcher.(*Engine).DocumentWorkerExec(0x0?, 0x0?)
        /home/runner/work/gofound/gofound/searcher/engine.go:125 +0x45
created by gofound/searcher.(*Engine).Init
        /home/runner/work/gofound/gofound/searcher/engine.go:71 +0x24a
```

**Comment by synodriver** [comment]
同时还会出现索引删不掉的情况，在webui找的到但是不能删
![image](https://user-images.githubusercontent.com/50922489/168838700-710d0af3-6b15-4c1e-936f-5c1969dcc972.png)

**Comment by zhangchunlin** [comment]
删除有问题的我也碰到了，之前先报在 gofound-python （ https://github.com/newpanjing/gofound-python/issues/3 ） ，但发现admin也有这个问题，所以应该是 gofound 的问题

**Comment by XiaoK29** [comment]
更新一下版本，这个bug已经修复
